# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   socket: /tmp/mysql.sock

default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5
  
development:
  <<: *default
  database: subsctime_app_development

# Do not set this db to the same as development or production.
test:
  <<: *default
  database: subsctime_app_test


production:
  <<: *default
  database: subsctime_app_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  # socket: /var/lib/mysql/mysql.sock
  host: subsctimedb3.camhna89eb2n.ap-northeast-1.rds.amazonaws.com
